### ISSUE TITLE
8.0 Version or show how you activated Offline Accounts

### ISSUE THREAD

**Issue by FormunaGit** [Pegoku/PrismLauncher-cracked#2]
### Role

I like quickly downloading mods.

### Suggestion

I want the launcher to be updated to 8.0, or maybe you show how to re-activate offline accounts.

### Benefit

so that people can get the latest version of PrismLauncher without having to lose cracked accounts

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Pegoku** [comment]
If you want to use the lates launcher version, you could get the source code and just remove the check for online accounts. I mean, you just need to change something like this: 
```
if (premiumAccountExists):
    allowAddCracked
else:
    noPremiumAccountAddedMsg
```
to:
```
if (premiumAccountExists):
    allowAddCracked
else:
    allowAddCracked
```

**Comment by FormunaGit** [comment]
Oh hi again, I found a method on how to bypass the online account this this doohickey [https://rentry.co/Prism4Free](https://rentry.co/Prism4Free)
